name: CI Tasks
on: pull_request

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.x"
      - run: go mod tidy && go mod vendor
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49
      - run: make go/test
      - run: make go/lint
  run-smoketest:
    name: Run Smoketest
    runs-on: ubuntu-20.04
    services:
      opensearch:
        image: opensearchproject/opensearch:1.3.6
        ports:
          - 9200:9200
          - 9600:9600
        options: >-
          -e "discovery.type=single-node" 
          -e "plugins.security.disabled=true"
      opensearch_dashboards:
        image: opensearchproject/opensearch-dashboards:1.3.6
        ports:
          - 5601:5601
        env:
          OPENSEARCH_HOSTS: "[\"http://opensearch:9200\"]"
          DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.x"
      - run: make smoke_test
